export const DomainEvents = {
  TaskCreated: "task.created",
  TaskAssigned: "task.assigned",
  TaskSubmitted: "task.submitted",
  TaskVerified: "task.verified",
  TaskCompleted: "task.completed",
  TaskValidationFailed: "task.validation_failed",

  MissionCreated: "mission.created",
  MissionClaimed: "mission.claimed",
  MissionExecutionStepAppended: "mission.execution_step_appended",
  MissionEvidenceSubmitted: "mission.evidence_submitted",
  MissionVerdictRecorded: "mission.verdict_recorded",
  MissionChallengeOpened: "mission.challenge_opened",
  MissionChallengeResolved: "mission.challenge_resolved",
  MissionEscalated: "mission.escalated",
  MissionRetried: "mission.retried",
  MissionSettled: "mission.settled",
  MissionFailed: "mission.failed",

  HeartbeatTaskRegistered: "heartbeat.task_registered",
  HeartbeatTaskExecuted: "heartbeat.task_executed",
  HeartbeatTaskDisabled: "heartbeat.task_disabled",
  HeartbeatTaskEnabled: "heartbeat.task_enabled",
} as const;
